version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Credito.ScoreEngine.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - credito-network

networks:
  credito-network:
    driver: bridge